package com.sissi.pluggableannotationprocessordemo;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;

import com.sissi.annotation.GenFile;

import java.util.Map;

@GenFile(packageName = "com.sissi.pluggableannotationprocessordemo",
        className = "ReqRspMap$$AutoGenerated")
public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

//        GenFile genFile = MainActivity.class.getAnnotation(GenFile.class);
//        Class.forName(genFile.packageName()+"."+genFile.className());

        Map<String, Integer> timeoutMap = ReqRspMap$$AutoGenerated.reqTimeoutMap;
        for (String key : timeoutMap.keySet()){
//            Log.i("", "key="+key+" timeout="+timeoutMap.get(key));
            PcTrace.p("key="+key+" timeout="+timeoutMap.get(key));
        }
//        Log.i("", ReqRspMap$$FromAnnotation.getReqRspsMap());
    }
}
